name: aifarma
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ^3.35.4

dependencies:
  archive: ^4.0.7
  chopper: ^8.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  drift: ^2.22.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_html: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_markdown_plus: ^1.0.5
  flutter_portal: ^1.1.4
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  # gpt_markdown: ^1.1.4
  gpt_markdown:
    path: ../gpt_markdown
  hooks_riverpod: ^3.0.3
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.2.0
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  retrofit: ^4.7.3
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  build_runner: ^2.7.1
  carapacik_lints: ^1.13.0
  chopper_generator: ^8.0.3
  custom_lint: ^0.8.1
  drift_dev: ^2.22.0
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  image_res: ^0.3.0
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  swagger_dart_code_generator: ^4.0.2

dependency_overrides:
  #   build: ^3.0.0
  analyzer: ^8.4.0
  # dart_style: ^3.1.2
  #   source_gen: ^1.5.0
  # swagger_dart_code_generator:
  #   path: ../swagger-dart-code-generator
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/google_fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Rubik-Medium.ttf
          weight: 600
        - asset: assets/google_fonts/Rubik-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_foreground_inset: 0
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  image_path: assets/images/app_icon.png
